version: '3'
services:
  cs101_server:
    restart: always
    build: .
    command: uvicorn serve:app --port 8080
  candy_reverse:
    image: candy:latest
    ports:
      - "80:80"
      - "443:443"
    command: caddy reverse_proxy --from cs101.fengtao.xyz --to cs101_server:8080
